### ISSUE TITLE
ValueError: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by developeralgo8888** [lukovkin/ufcnn-keras#3]
Error occurs after the first run (50 epochs)  is completed on the first training & signal files. This is the commit before the current commit. I am going to do a quick run of the current commit to see if i run into any issues.

Traceback (most recent call last):
  File "UFCNN1.py", line 596, in <module>
    case_tc = train_and_predict_classification(UFCNN_TC, features=features, output_dim=output_dim, sequence_length=sequence_length, epochs=50, training_count=10, testing_count = 6 )
  File "UFCNN1.py", line 511, in train_and_predict_classification
    xdim, ydim = yp.shape
ValueError: too many values to unpack (expected 2)

**Comment by lukovkin** [comment]
train_and_predict_classification is yet not stable, use 'python UFCNN1.py
tradcom_simple' or in notebook accordingly.
You can try with more epochs for example.

Best regards,

Dmitry Lukovkin
Deep Gnosis
http://stocksneural.net
Tel. +7 903 750 2976
Skype: dmitry.lukovkin

**Comment by developeralgo8888** [comment]
Hi Dmitry, 
FYI,
i tested the tradcom_simple but the optimizer is not stable if you increase the epochs. I played around with Epochs = 50 , 100, 200, 300 , 400  but as you increase the epochs and start a fresh . Making sure to delete all the training files created in the previous tests. I get  NAN as it goes to converge after 150 epochs but then when i do same test it converges without NAN or it stays at 0.4137 with no change. so it is a little unstable.

**Comment by ErnstTmp** [comment]
Hi Developer,
I have seen the same behaviour. I think it has to do with the RELU 
activations, but the others do not work because of a bug. I hope it is 
getting fixed.

Cheers,
Ernst

**Comment by lukovkin** [comment]
OK, we are not 100% sure about signals yet, list of features, etc. And multiday training started working just now.
So it's OK for now, I think.

**Comment by hackerwei** [comment]
Hi Dmitry:
Does the UFCNN simulation show that CNN works better than LSTM RNN? I have read the paper, but I take a sceptical attitude.
