### ISSUE TITLE
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

### ISSUE THREAD

**Issue by developeralgo8888** [lukovkin/ufcnn-keras#4]
Getting type error on the current Commit.

Using Theano backend.
Using gpu device 6: GeForce GTX TITAN X (CNMeM is enabled with initial size: 90.0% of memory, CuDNN 4004)
/home/anaconda3/lib/python3.5/site-packages/theano/tensor/signal/downsample.py:5: UserWarning: downsample module has been moved to the pool module.
  warnings.warn("downsample module has been moved to the pool module.")
Running model:  tradcom
Traceback (most recent call last):
  File "UFCNN1.py", line 623, in <module>
    loss="categorical_crossentropy", sequence_length=sequence_length, optimizer=sgd )
  File "UFCNN1.py", line 215, in ufcnn_model
    init)
  File "UFCNN1.py", line 131, in ufcnn_model_concat
    model.add_node(Convolution1D(nb_filter=nb_filter, filter_length=filter_length, border_mode='valid', init=init, input_shape=(sequence_length, features)), name='conv1', input='input_padding')
  File "/home/anaconda3/lib/python3.5/site-packages/keras/layers/containers.py", line 359, in add_node
    layer.set_previous(self.nodes[input])
  File "/home/anaconda3/lib/python3.5/site-packages/keras/layers/core.py", line 98, in set_previous
    assert self.input_ndim == len(layer.output_shape), ('Incompatible shapes: layer expected input with ndim=' +
  File "/home/anaconda3/lib/python3.5/site-packages/keras/layers/convolutional.py", line 707, in output_shape
    input_shape[1] + self.padding \* 2,
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

**Comment by lukovkin** [comment]
Works on Python 2.7, Python 3.5 on CPU with latest master branch of Keras.
Please check.

**Comment by developeralgo8888** [comment]
Upgraded Keras 0.3.2 master branch from the source

**Comment by developeralgo8888** [comment]
Issue resolved
